### PR TITLE
fix: Incorrect Bounds Calculation in Circuit-to-SVG

### LINKED ISSUE #168: Incorrect Bounds Calculation in Circuit-to-SVG, Affects View Window Display
Image

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #168
Fixes #168

### CODE REVIEW

File: lib/pcb/convert-circuit-json-to-pcb-svg.ts [hunk 1]
```diff
@@ -211,6 +217,64 @@ export function convertCircuitJsonToPcbSvg(
       maxY = Math.max(maxY, point.y)
     }
   }
+
+  // UPDATED: Account for different property names for silkscreen elements
+  function updateSilkscreenBounds(silkscreenItem: any) {
```
Comment (seveibar) [inline lib/pcb/convert-circuit-json-to-pcb-svg.ts:222]: be better with the type definition here, your unnecessarily complex because of the `any`

**Review by seveibar — CHANGES_REQUESTED** [review]
☂️

File: lib/pcb/convert-circuit-json-to-pcb-svg.ts [hunk 2]
```diff
@@ -211,6 +218,21 @@ export function convertCircuitJsonToPcbSvg(
...
+    } else if (item.type === "pcb_silkscreen_path") {
+      updateTraceBounds(item.route)
+    } else if (item.type === "pcb_silkscreen_rect") {
+      updateBounds(item.center, item.width, item.height)
+    } else if (item.type === "pcb_silkscreen_circle") {
+      updateBounds(item.center, item.radius * 2, item.radius * 2)
+    } else if (item.type === "pcb_silkscreen_line") {
+      updateBounds({ x: item.x1, y: item.y1 }, 0, 0)
+      updateBounds({ x: item.x2, y: item.y2 }, 0, 0)
+    }
```
Comment (seveibar) [inline lib/pcb/convert-circuit-json-to-pcb-svg.ts:234]: wow this code is so much cleaner now!

**Review by seveibar — APPROVED** [review]
kind of a silly "double check" on the type but wtvr
